version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

jobs:
  deploy-heroku:
    executor: heroku/default

    steps:
      - checkout

      - heroku/install

      - heroku/deploy-via-git:
          app-name: "joke-api-iw3"

  docker-push:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # with credentials stored in the UI
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin

      # build the application image
      - run: docker build -t $DOCKER_LOGIN/joke-app:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push $DOCKER_LOGIN/joke-app:$CIRCLE_BRANCH

workflows:
  deploy:
    jobs:
      - node/test:
          filters:
            branches:
              only:
                - circleci

      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci

      - deploy-heroku:
          requires:
            - "node/test"
            - "node/run"
          filters:
            branches:
              only:
                - circleci

      - docker-push:
          requires:
            - "node/test"
            - "node/run"
          filters:
            branches:
              only:
                - circleci
