version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  docker:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # with credentials stored in the UI
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin

      # build the application image
      - run: docker build -t $DOCKER_LOGIN/joke-api:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push $DOCKER_LOGIN/joke-api:$CIRCLE_BRANCH

workflows:
  build-test-deploy:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci
                
      - node/test:
          filters:
            branches:
              only:
                - circleci

      - heroku/deploy-via-git:
          requires:
            - node/run
            - node/test
          app-name: "joke-app-iw4"
          filters:
            branches:
              only:
                - circleci

      - docker:
          filters:
            branches:
              only:
                - circleci

  